eth:
  outputs:
    ci:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_IDENTIFIER') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
      database: ci
      private_key_path: "{{ env_var('DBT_PRIVATE_KEY_PATH') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 1
      warehouse: COMPUTE_WH