airstats:
  outputs:
    ci:
      type: snowflake
      account: OWSABVL-IP00020
      user: dbt
      role: TRANSFORM
      database: CI
      private_key: "{{ env_var('DBT_PRIVATE_KEY') }}"
      private_key_passphrase: q
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 1
      warehouse: COMPUTE_WH
  target: ci