airstats:
  outputs:
    ci:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_IDENTIFIER') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
      database: CI
      private_key: "{{ env_var('DBT_PRIVATE_KEY') }}"
      private_key_passphrase: q
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 1
      warehouse: COMPUTE_WH
  target: ci